### ISSUE TITLE
Bad instruction for transactions

### ISSUE THREAD

**Issue by euenf** [RealEstateAssetLedger/real_contract#2]
Hi,

I'm experiencing an error whenever I try to create a transaction for my REAL tokens.

The error is as follows:
Warning! Error encountered during contract execution [Bad instruction] 

It seems as if all transactions have been failing for the past couple of days:
https://etherscan.io/address/0x9214ec02cb71cba0ada6896b8da260736a67ab10

Any idea what I can do?

Thanks

**Comment by JDragsil** [comment]
Hi, the tokens transfer is not already open, it will be opened this Friday
